# Use the official Python image as a base image
FROM python:3.9-slim

# Set the working directory inside the container
WORKDIR /app

# Copy requirements.txt into the container
COPY requirements.txt .

# Install the dependencies from requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code into the container
COPY . .

# CMD ["python", "run.py"]

# Command to run the app (using gunicorn for production)
CMD ["gunicorn", "-w", "4", "run:app"]
